config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  
  devise_for :gyms, controllers: {
    sessions: 'gyms/sessions'
  }

  namespace :gyms do
    resources :favorites, only: [:index]
    resources :climbers, only: [:index, :destroy]
    # resources :gyms, only: [:edit, :update]
    resources :genres, only: [:create, :index, :destroy, :show, :edit, :update]
    resources :grades, only: [:create, :index, :destroy, :edit, :update]
    resources :tasks, only: [:create, :index, :destroy, :edit, :update]
    resources :infos, only: [:create, :index, :destroy, :edit, :update]
    resources :done_tasks, only: [:index]
  end
  # urlにgymsを含めたくないのでわざとnamespaceから外してます
  scope module: :gyms do
    resources :gyms, only: [:edit, :update]
  end

  devise_for :climbers, controllers: {
    sessions: 'climbers/sessions',
    registrations: 'climbers/registrations',
    passwords: 'climbers/passwords'
  }

  scope module: :climbers do
    get 'gyms/search' => 'gyms#search'
    get 'gyms/rank/:id' => 'gyms#rank', as: :rank
    get 'climbers/trophy/:id' => 'climbers#trophy', as: :trophy
    get 'climbers/search' => 'climbers#search', as: :climber_search
    get 'following_climbers' => 'climbers#following_climbers'
    resources :climbers, only: [:show, :edit, :update, :index] do
      member do
        get :follower, :following
      end
    end
    resources :favorites, only: [:index] do
      get 'gym_favo' => 'favorites#gym_favo', as: :gym_favo
    end
    resources :gyms, only: [:index, :show], shallow: true do
      resource :favorites, only: [:create, :destroy]
      get :favorites, on: :collection
    end
  end
    # urlにclimbersを含めたくないのでわざとscopeから外してます
    get 'homes/about' => 'homes#about', as: :about
    get 'homes/top' => 'homes#top', as: :top
    post '/homes/guest_sign_in', to: 'homes#new_guest'

    resources :genres, only: [:create, :index, :destroy, :new, :show, :edit, :update]
    resources :tasks, only: [:show]
    resources :infos, only: [:index]
    resources :done_tasks, only: [:index, :create, :update, :destroy]
    resources :trophys, only: [:create]
    resources :relationships, only: [:create, :destroy]
    resources :battles, only: [:create, :destroy, :update, :index]
    resources :notifications, only: [:create, :destroy, :update, :index]
    resources :battle_historys, only: [:create, :index]
end

app/models/battle_history.rb
class BattleHistory < ApplicationRecord

  belongs_to :winner, class_name: 'Climber'
  belongs_to :loser, class_name: 'Climber'
 
  def result_battle_is_win
    if self.is_draw_status == false
      p = 'win'
    else
      p = '引き分け'
    end
  end
end

app/controllers/battle_historys_controller.rb
class BattleHistorysController < ApplicationController
	before_action :authenticate_climber!

  def index
  end

  def create
  end

  def battle_historie_params
    params.permit(:winner_id, :winner_count, :loser_id, :loser_count, :is_draw_status, :started_at, :finished_at, :present_trophy_id)
  end
end

app/helpers/battle_historys_helper.rb
module BattleHistorysHelper
end

app/views/battle_historys/_battle_history.html.erb
<h2>
  バトル履歴一覧
</h2>
  <% if current_climber.win_count == nil %>
    まだ勝負をしてません
  <% else %>
  <h4 class="feature-title">
    勝負数 <%= my_win = current_climber.win_count + current_climber.win_count %>回
    勝利数 <%= current_climber.win_count %>回
    勝率 <%= ((current_climber.win_count.to_f) / (my_win)).floor(2)  %></p>
  </h4>

  <% end %>
    <table class="table">
      <thead>
        <tr>
          <th>バトル開始日</th>
          <th>バトル終了日</th>
          <th></th>
          <th>対戦相手</th>
          <th>勝敗</th>
          <th>自分の登った本数</th>
          <th>相手の登った本数</th>
        </tr>
      </thead>
      <tbody>
      <% battle_historys.each do |battle_history| %>
        <% if battle_history.present? && battle_history.winner.present? %>
          <tr>
              <td>
                <%= battle_history.started_at.strftime("%Y/%m/%d") %>
              </td>
              <td>
                <%= battle_history.created_at.strftime("%Y/%m/%d")%>
              </td>
          <%# カレントユーザが勝負を申し込まれた場合 #%>
          <% if (current_climber == battle_history.winner) %>
            <td>
              <%= link_to climber_path(battle_history.loser.id) do %>
                  <%= attachment_image_tag battle_history.loser,:profile_image, format: 'jpeg', class: "profile-icon", fallback: asset_path("no_image.png"), size:'40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to climber_path(battle_history.loser.id) do %>
                  <%= battle_history.loser.name %>
              <% end %>
            </td>
            <td>
              <% if battle_history.is_draw_status == false %>
            <%= image_tag 'winn.png' %> Win 
            <% else%>
            <i class="fas fa-balance-scale"></i>
              Draw
            <i class="fas fa-balance-scale"></i>
            <% end %>
            </td>
            <td>
              <%= battle_history.winner_count%>本
            </td>
            <td>
              <%= battle_history.loser_count%>本
            </td>
          <% elsif (current_climber == battle_history.loser) %>
            <td>
              <%= link_to climber_path(battle_history.winner.id) do %>
                  <%= attachment_image_tag battle_history.winner,:profile_image, format: 'jpeg', class: "profile-icon", fallback: asset_path("no_image.png"), size:'40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to climber_path(battle_history.winner.id) do %>
                  <%= battle_history.winner.name %>
              <% end %>
            </td>
            <td>
            <% if battle_history.is_draw_status == false %>
                <%= image_tag 'kinoko.png' %> Lose
            <% else%>
              <i class="fas fa-balance-scale"></i>
                Draw
              <i class="fas fa-balance-scale"></i>
            <% end %>
            </td>
            <td>
              <%= battle_history.loser_count %>本
            </td>
            <td>
            <%= battle_history.winner_count %>本
            </td>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
<div class="centering_item">
  <%= paginate battle_historys %>
</div>

app/views/battle_historys/index.html.erb
<div class="container">
  <h1>バトル履歴</h1>
  <%= render 'battle_history', battle_historys: @battle_historys %>
</div>