config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  
  devise_for :gyms, controllers: {
    sessions: 'gyms/sessions'
  }

  namespace :gyms do
    resources :favorites, only: [:index]
    resources :climbers, only: [:index, :destroy]
    # resources :gyms, only: [:edit, :update]
    resources :genres, only: [:create, :index, :destroy, :show, :edit, :update]
    resources :grades, only: [:create, :index, :destroy, :edit, :update]
    resources :tasks, only: [:create, :index, :destroy, :edit, :update]
    resources :infos, only: [:create, :index, :destroy, :edit, :update]
    resources :done_tasks, only: [:index]
  end
  # urlにgymsを含めたくないのでわざとnamespaceから外してます
  scope module: :gyms do
    resources :gyms, only: [:edit, :update]
  end

  devise_for :climbers, controllers: {
    sessions: 'climbers/sessions',
    registrations: 'climbers/registrations',
    passwords: 'climbers/passwords'
  }

  scope module: :climbers do
    get 'gyms/search' => 'gyms#search'
    get 'gyms/rank/:id' => 'gyms#rank', as: :rank
    get 'climbers/trophy/:id' => 'climbers#trophy', as: :trophy
    get 'climbers/search' => 'climbers#search', as: :climber_search
    get 'following_climbers' => 'climbers#following_climbers'
    resources :climbers, only: [:show, :edit, :update, :index] do
      member do
        get :follower, :following
      end
    end
    resources :favorites, only: [:index] do
      get 'gym_favo' => 'favorites#gym_favo', as: :gym_favo
    end
    resources :gyms, only: [:index, :show], shallow: true do
      resource :favorites, only: [:create, :destroy]
      get :favorites, on: :collection
    end
  end
    # urlにclimbersを含めたくないのでわざとscopeから外してます
    get 'homes/about' => 'homes#about', as: :about
    get 'homes/top' => 'homes#top', as: :top
    post '/homes/guest_sign_in', to: 'homes#new_guest'

    resources :genres, only: [:create, :index, :destroy, :new, :show, :edit, :update]
    resources :tasks, only: [:show]
    resources :infos, only: [:index]
    resources :done_tasks, only: [:index, :create, :update, :destroy]
    resources :trophys, only: [:create]
    resources :relationships, only: [:create, :destroy]
    resources :battles, only: [:create, :destroy, :update, :index]
    resources :notifications, only: [:create, :destroy, :update, :index]
    resources :battle_historys, only: [:create, :index]
end

app/models/climber.rb
class Climber < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :done_tasks, dependent: :destroy
  has_many :trophies, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :gym_favorites, through: :favorites, source: :gym

  # バトル履歴
  #  勝者
  has_many :winner, class_name: 'BattleHistorie', foreign_key: 'winner_id'
  #  敗者
  has_many :loser, class_name: 'BattleHistorie', foreign_key: 'loser_id'

  # バトル機能
  #  挑む側
  has_many :battles, class_name: 'Battle', foreign_key: 'climber_id'
  #  挑まれる側
  has_many :battlers, class_name: 'Battle', foreign_key: 'battler_id'
  # 挑んでいる
  has_many :battlwers, through: :battles, source: :climber
  # 挑まれている
  has_many :battlwings, through: :battlers, source: :battler

  # 通知機能
  #  送る側
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  #  送られる側
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  # フォロー、フォロワー機能
  has_many :relationships, class_name: 'Relationship', foreign_key: 'climber_id'
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  # フォローされている数
  has_many :followers, through: :reverse_of_relationships, source: :climber
  # フォローしてる数
  has_many :followings, through: :relationships, source: :follow

  validates :name, presence: true, length: {maximum: 10, minimum: 2}
  validates :introduction, length:{ maximum: 30}

  def follow(other_climber)
    # フォローしようとしている other_climber が自分自身ではないかを検証
    unless self == other_climber
      # self = current_climber
      # find_or_create_by = 保存
      relationships.find_or_create_by(follow_id: other_climber)
    end
  end

  # フォローがあればアンフォローする
  def unfollow(other_climber)
    relationship = relationships.find_by(follow_id: other_climber.id)
    # relationship が存在すれば destroy します
    relationship.destroy if relationship
  end

  # self.followings によりフォローしている climber 達を取得し、
  # include?(other_climber) によって other_climber が含まれていないかを確認
  def following?(other_climber)
    followings.include?(other_climber)
  end

  def follows_by?(climber)
    relationships.where(climber_id: climber.id).exists?
  end

  # gymをお気に入りにしているか判定をする
  # climberにはcurrent_climberが渡される
  def favorite_by?(climber)
    favorites.where(climber_id: climber.id).exists?
  end

  # バトルを申請しているか判定する
  def battle_now?(other_climber)
    battles.where(battler_id: other_climber.id).exists?
  end

  # バトル申請をしていた場合は解除する
  def unbattle?(other_climber)
    battle = battles.find_by(battler_id: other_climber.id)
    # battle が存在すれば destroy します
    battle.destroy if battle
  end

  def month_done_tasks
    now = Time.current
    DoneTask.where(climber_id: self.id,created_at: (now.beginning_of_month)..(now.end_of_month))
  end

  def my_trophys_by
    now = Time.current
    Trophy.where(
      climber_id: self.id,
      created_at: (now.beginning_of_month)..(now.end_of_month))
  end
end

app/controllers/climbers/climbers_controller.rb
class Climbers::ClimbersController < ApplicationController
  before_action :authenticate_climber!
  before_action :ensure_correct_climber, {only: [:edit, :update]}
  before_action :set_climber, only: %i[show edit update following follower trophy]
  before_action :forbid_test_climber, {only: [:edit,:update]}

  def show
    now = Time.current
    @favorites = Favorite.where(climber_id: @climber.id)
    @new_battle = Battle.new
    @notifications = current_climber.passive_notifications.page(params[:page]).per(10)
    # battleのidを渡す
    ＠unbattle = Battle.find_by(battler_id: @climber.id)
  end

  def index
    @climbers = Climber.all.page(params[:page]).per(8)
    if params[:name].present?
      @climbers_search = Climber.where('name LIKE ?', "%#{params[:name]}%")
    else
      @climbers_search = Climber.all.page(params[:page]).per(8)
    end
  end

  def edit
  end

  def update
    if @climber.update(climber_params)
      redirect_to climber_path(@climber), notice: 'プロフィールをupdateしました！'
    else
      render :edit
    end
  end

  # フォローしている人
  def following
    @climbers = @climber.followings
    render 'show_follow'
  end

  # フォローしてくれてる人
  def follower
    @climbers = @climber.followers
    render 'show_follower'
  end

  def trophy
    ActiveRecord::Base.uncached do
      @trophys = Trophy.where(climber_id: @climber.id).page(params[:page]).per(6)
    end
  end

  def search
    if params[:name].present?
      @climbers = Climber.where('name LIKE ?', "%#{params[:name]}%").page(params[:page]).per(8)
    else
      @climbers = Climber.all.page(params[:page]).per(8)
    end
  end

  private
  def set_climber
    @climber = Climber.find(params[:id])
  end

  # ※カレントユーザー以外は直接リンクを入力しても編集ページにいけないようにする
  def ensure_correct_climber
    @climber = Climber.find(params[:id])
    if current_climber.id != @climber.id
      redirect_to edit_climber_path(current_climber)
    end
  end

  def forbid_test_climber
    if @climber.email == "guest@example.com"
      flash[:notice] = "ゲストユーザーのため変更できません"
      redirect_to climber_path(current_climber)
    end
end

  def climber_params
    params.require(:climber).permit(:name, :profile_image, :email, :introduction)
  end
end

app/controllers/climbers/confirmations_controller.rb
# frozen_string_literal: true

class Climbers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/climbers/favorites_controller.rb
class Climbers::FavoritesController < ApplicationController
before_action :authenticate_climber!, :only => [:create, :destroy]
before_action :set_gym, only: %i[create destroy]
  # before_action :ensure_correct_climber, {only: [:create, :destroy, :index]}

  def create
    favorite = current_climber.favorites.build(gym_id: params[:gym_id])
    favorite.save!
  end

  def destroy
    favorite = current_climber.favorites.find_by(gym_id: params[:gym_id])
    favorite.destroy
  end

  def index
    @favorites = Favorite.where(climber_id: current_climber.id).page(params[:page]).per(10)
  end

  def gym_favo
    @gym_favo = Gym.find(params[:favorite_id])
    @favorites = Favorite.where(gym_id: @gym_favo.id).page(params[:page]).per(6)
  end

  private
  def set_gym
    @gym = Gym.find(params[:gym_id])
  end

  def favorite_params
    params.require(:favorite).permit(:climber_id, :gym_id)
  end
end

app/controllers/climbers/gyms_controller.rb
class Climbers::GymsController < ApplicationController
# authenticate_user！でログイン認証されてない場合home画面へリダイレクトとする
before_action :authenticate_climber!, :only => [:rank, :favorites]
before_action :set_climber_gym, only: %i[show rank]

  def index
    @gyms = Gym.all.page(params[:page]).per(6)
    @genres = Genre.all
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @gyms = @genre.gyms.page(params[:page]).order('updated_at DESC').page(params[:page]).per(6)
    else
      @gyms = Gym.page(params[:page]).order('updated_at DESC').page(params[:page]).per(6)
    end
  end

  def rank
    # ジムの中の登れた課題ランキング
    now = Time.current
    @gym_done_tasks = @gym.gym_done_tasks_by
    # ジム内の自分の順位
    @gym_my_rank = 1
    # @rank_done_task（多い順に並んでいる）にあるclimber_idとcurrent_climber.idが一致するまで1ずつ増やすことで順位を出す
    @gym_done_tasks.each do |rank|
      break if rank.climber_id == current_climber.id
        @gym_my_rank += 1
      end
    # 全ジムの登れた課題ランキング
    @all_done_tasks = all_done_tasks_by
    # 全てのジム内の自分の順位
    @all_my_rank = 1
    @all_done_tasks.each do |rank|
      break if rank.climber_id == current_climber.id
        @all_my_rank += 1
      end
  end

  def show
    @tasks = @gym.tasks
    @grades_all = Grade.all
  end

  def favorites
    # gym_favorites = climberモデルに記述.gymモデルを参照する
    @gyms = current_climber.gym_favorites.includes(:climber).recent
  end

  def search
    @genres = Genre.all
    # 値が入力されていれば、whereメソッドと部分一致検索で、店舗情報を取得する。
    @gyms = if params[:gym_name]
              Gym.where('gym_name LIKE ?', "%#{params[:gym_name]}%").page(params[:page]).per(6)
            else
              Gym.all.page(params[:page]).per(6)
            end
  end

  private
  def set_climber_gym
    @gym = Gym.find(params[:id])
  end

  # 全部のジムの登れた課題ランキング
  def all_done_tasks_by
    now = Time.current
    DoneTask.find(
    DoneTask.where(
      created_at:(now.beginning_of_month)..(now.end_of_month))
      .group(:climber_id)
      .order('count(task_id) desc')
      .limit(30)
      .pluck(:id))
  end

  def gym_params
    params.require(:gym).permit(:genre_id, :description, :gym_name, :post_code, :address, :gym_url, :gym_image)
  end
end

app/controllers/climbers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Climbers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/climbers/passwords_controller.rb
# frozen_string_literal: true

class Climbers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/climbers/registrations_controller.rb
# frozen_string_literal: true

class Climbers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/climbers/sessions_controller.rb
# frozen_string_literal: true

class Climbers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/climbers/unlocks_controller.rb
# frozen_string_literal: true

class Climbers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/gyms/climbers_controller.rb
class Gyms::ClimbersController < ApplicationController
  before_action :authenticate_gym!

  def index
    @climbers = Climber.all
  end

  def destroy
    @climber = Climber.find(params[:id])
    @climber.destroy
    redirect_to request.referrer || gyms_url, notice: 'ユーザーを退会させました'
  end

  private
  def climber_params
    params.require(:climber).permit(:name, :profile_image, :introduction, :email)
  end
end

app/helpers/climbers/climbers_helper.rb
module Climbers::ClimbersHelper
end

app/helpers/climbers/done_tasks_helper.rb
module Climbers::DoneTasksHelper
end

app/helpers/climbers/favorites_helper.rb
module Climbers::FavoritesHelper
end

app/helpers/climbers/grades_helper.rb
module Climbers::GradesHelper
end

app/helpers/climbers/gyms_helper.rb
module Climbers::GymsHelper
end

app/helpers/climbers/tasks_helper.rb
module Climbers::TasksHelper
end

app/helpers/climbers/trophys_helper.rb
module Climbers::TrophysHelper
end

app/helpers/gyms/climbers_helper.rb
module Gyms::ClimbersHelper
end

app/views/climbers/climbers/_battle_now.html.erb
  <% if current_climber.battle_now?(climber) %>
    <% @unbattle = Battle.find_by(climber_id: current_climber.id, battler_id: climber.id) %>
    <%= form_with method: :delete, local: true, url:battle_path(@unbattle.id) do |f| %>
    <%= hidden_field_tag :battler_id, climber.id %>
      <%= f.button :type => "submit", style: 'border-style: none;',class: 'btn btn-unbattle' do %>
        <i class="fas fa-tint"> バトルを取り消す</i>
      <% end %>
    <% end %>
  <% else %>
      <%= form_with method: :post, model: @new_battle,local: true, url:battles_path do |f| %>
        <%= hidden_field_tag :battler_id, climber.id %>
          <%= f.button :type => "submit", style: 'border-style: none;',class: 'btn btn-battle' do %>
            <i class="fas fa-fire-alt"> バトルを申し込む</i>
          <% end %>
      <% end %>
  <% end %>

app/views/climbers/climbers/_climbers.html.erb
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                名前
            </th>
            <th>
                今月登った本数
            </th>
            <th>
                フォロー
            </th>
            <th>
                バトル
            </th>
        </tr>
    </thead>
    <tbody>
        <% climbers.each do |climber| %>
        <tr>
            <td>
              <%= link_to climber_path(climber.id) do %>
                <%= attachment_image_tag climber,:profile_image, format: 'jpeg', class: "profile-icon", fallback: asset_path("no_image.png"), size:'40x40' %>
              <% end %>
            </td>
            <td>
                <%= link_to climber_path(climber.id) do %>
                  <%= climber.name%>
                <% end %>
            </td>
            <td>
                <%= climber.month_done_tasks.count %> 本
            </td>
              <% unless current_climber.id == climber.id %>
            <td>
              <%= render 'follow_unfollow', climber: climber %>
            </td>
            <td>
              <%= render 'battle_now', climber: climber %>
            </td>
            <% end %>
            <td></td>
            <td></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/climbers/climbers/_follow_unfollow.html.erb
<% if current_climber.following?(climber) %>
  <%= form_for(current_climber.relationships.find_by(follow_id: climber.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :follow_id, climber.id %>
        <%= f.button :type => "submit", style: 'border-style: none;',class: 'btn btn-danger' do %>
          <i class="fas fa-user-minus"> フォロー 中</i>
        <% end %>
    <% end %>
<% else %>
  <%= form_for(current_climber.relationships.build) do |f| %>
    <%= hidden_field_tag :follow_id, climber.id %>
        <%= f.button :type => "submit", style: 'border-style: none;',class: 'btn btn-primary' do %>
          <i class="fas fa-user-plus"> フォローする</i>
        <% end %>
    <% end %>
<% end %>

app/views/climbers/climbers/_notification.html.erb
<% notifications.each do |notification| %>
  <% visiter = notification.visiter %>
  <% battle = notification.battle %>

  <div class="user-view clearfix ">
    <%= link_to climber_path(visiter) do %>
      通知があります
    <% end %>
    <span class="moderate-font">
      <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
    </span>
    <br>
    <% if !@battle.nil? %>
      <p class="moderate-font">
        <%= @battle %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/climbers/climbers/edit.html.erb
<div class="container">
  <div class="content">
    <% if @climber.errors.any? %>
      <div class="alert alert-danger">
        <h2>
          <%= @climber.errors.count %>件の空白があります
        </h2>
        <% @climber.errors.full_messages.each do |message| %>
          <%= message %><br>
        <% end %>
      </div>
    <% end %>
    <h1>登録情報編集</h1>
      <%= form_with method: :patch, model: @climber, url:climber_path(@climber.id), local: true do |f| %>
        <div class="field row">
          <%= f.label :name, "プロフィール画像" %>
          <%= f.attachment_field :profile_image, placeholder:"プロフィール画像", id:"profile_icon" %>
        </div>

        <div class="field row">
          <%= f.label :name, "名前" %>
          <%= f.text_field :name %>
        </div>

        <div class="field row">
          <%= f.label :introduction, "自己紹介" %>
          <%= f.text_area :introduction,{placeholder: "30文字以内で一言！"} %>
        </div>

        <div class="field row">
          <%= f.label :email, "メールアドレス" %>
          <%= f.text_field :email %>
        </div>

        <div class="action row">
          <%= f.submit '編集内容を保存する', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
</div>

app/views/climbers/climbers/index.html.erb
<div class="container">
  <%= render 'layouts/alert' %>
    <h1>
      クライマー 一覧
    </h1>
    <%= form_with url: climber_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :name,{placeholder: "名前で検索"} %>
      <%= f.button :type => "submit", style: 'border-style: none;',class: 'btn btn-success' do %>
        <i class="fa fa-search"></i>
      <% end %>
    <% end %>
    <section class="tasks">
        <h3>
          ここからバトルを申し込んだり、フォローすることができます
        </h3>
    </section>
    <%= render 'climbers', climbers: @climbers %>
    <div class="centering_item">
      <%= paginate @climbers %>
    </div>
</div>

app/views/climbers/climbers/search.html.erb
<div class="container">
  <h1>検索結果</h1>

  <%= form_with url: climber_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :name,{placeholder: "名前で検索"} %>
    <%= f.button :type => "submit", style: 'border-style: none;',class: 'btn btn-success' do %>
      <i class="fa fa-search"></i>
    <% end %>
  <% end %>
  <% unless @climbers.present? %>
    <h4>" <%= params[:name] %> " に一致するクライマーは見つかりませんでした</h4>
  <% end %>
    <section class="tasks">
    <h3>
      <%= link_to ">> ユーザ一覧ページへ",climbers_path %>
    </h3>
  </section>
 
  <%= render 'climbers', climbers: @climbers %>
  <div class="centering_item">
    <%= paginate @climbers %>
  </div>
</div>

app/views/climbers/climbers/show.html.erb
<div class="container">
	<div class="profile">
  <%= render 'layouts/alert' %>
		<div class="container">
			<p class="heading-p">
			<div class="prof-group">
        <div class="left-content">
          <div class="my-icon">
            <%= attachment_image_tag @climber, :profile_image, format: 'jpeg', class: "pull-left my-icon", fallback: asset_path("no_image.png") %>
          </div>
        </div>

        <div class="prof-vi">
          <h2 class="feature-title">
            <%= @climber.name %>
          </h2>
          <h3 class="feature-title">
            フォロワー <%= link_to @climber.followers.count,follower_climber_path(@climber) %>
            フォロー中 <%= link_to @climber.followings.count,following_climber_path(@climber) %>
            <%= link_to trophy_path(@climber) do %>
              <%= image_tag 'tororo.png' %>
            <% end %>
          </h3>
          <p class="heading-p">
            <div class="balloon1-left">
              <% if @climber.introduction.present? %>
                <%= @climber.introduction %>
              <% elsif %>
                <%= "よろしくお願いします" %>
              <% end %>
            </div>
            <% if current_climber.id == @climber.id %>
              <h3 class="feature-title">
              <%= link_to edit_climber_path do %>
                <%= image_tag 'purof.png' %>
                <%= link_to "プロフィール編集", edit_climber_path %>
              <% end %>
              </h3>
            <% else %>
              <h3 class="feature-title">
                <%= render 'climbers/climbers/battle_now', climber: @climber%>
                <%= render 'follow_unfollow', climber: @climber %>
              </h3>
            <% end %>
          </p>

        <div class="content">
          <h3 class="feature-favo">
          お気に入りジム</h3>
          <p class="heading-p">
            <% if @climber.favorite_by?(@climber) %>
                <% @favorites.each do |f|%>
                  <%= link_to gym_path(f.gym) do %>
                    <%= f.gym.gym_name %> /
                  <% end %>
                <% end %>
            <% else %>
              <p>まだお気に入りジムを登録していません</p>
            <% end %>
          </p>
          <% if current_climber.id == @climber.id %>
            <h3 class="feature-title">
              <%= link_to favorites_path do %>
                <%= image_tag 'info.png' %>
                <%= link_to "お気に入りジムからのお知らせ", favorites_path %>
              <% end %>
            </h3>
          <% end %>
          </div>

          </div>
        </div>
      </p>
    </div>
  </div>
</div>

app/views/climbers/climbers/show_follow.html.erb
<div class="container">
  <h1><%= @climber.name %> フォローユーザ</h1>
    <table class="table">
      <thead>
          <tr>
              <th></th>
              <th>名前</th>
              <th></th>
          </tr>
      </thead>
      <tbody>
        <% @climbers.each do |climber| %>
          <tr>
            <td>
              <%= link_to climber_path(climber.id) do %>
                <%= attachment_image_tag climber, :profile_image,format: 'jpeg', class: "profile-icon", fallback: asset_path("no_image.png") %>
              <% end %>
            </td>
            <td>
              <%= link_to climber_path(climber.id) do %>
                <%= climber.name %>
              <% end %>
            </td>
          <% unless current_climber.id == climber.id %>
            <td>
            <%= render 'climbers/climbers/battle_now', climber: climber%>
            </td>
            <td>
            <%= render 'follow_unfollow', climber: climber %>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
</div>

app/views/climbers/climbers/show_follower.html.erb
<div class="container">
  <h1><%= @climber.name %> フォロワー</h1>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>名前</th>
          <th>バトル</th>
          <th>フォロー</th>
        </tr>
      </thead>
      <tbody>
        <% @climbers.each do |climber| %>
        <tr>
            <td>
              <%= link_to climber_path(climber.id) do %>
                <%= attachment_image_tag climber, :profile_image,format: 'jpeg', class: "profile-icon", fallback: asset_path("no_image.png") %>
              <% end %>
            </td>
            <td>
              <%= link_to climber_path(climber.id) do %>
                <%= climber.name %>
              <% end %>
            </td>
            <% unless current_climber.id == climber.id %>
              <td>
                <%= render 'climbers/climbers/battle_now', climber: climber%>
              </td>
              <td>
                <%= render 'follow_unfollow', climber: climber %>
              </td>
            </tr>
            <% end %>
        <% end %>
      </tbody>
    </table>
</div>

app/views/climbers/climbers/trophy.html.erb
<div class="container">
  <div class="feature">
    <section id="feature">
      <h1>
        獲得したトロフィー
      </h1>

      <div class="strength-group clearfix">
        <% @trophys.each do |trophy| %>
          <div class="strength">
            <h3 class="feature-title">
              <%= trophy.my_trophy_name %>
            </h3>
              <%= attachment_image_tag trophy, :my_trophy_image, size: '100x100',format: "jpeg",fallback: asset_path("ira13.png") %>
            <h3 class="feature-title">
              <%= trophy.updated_at.strftime("%Y/%m/%d") %>
            </h3>
          </div>
        <% end %>
      </div>

      <div class="centering_item">
        <%= paginate @trophys %>
      </div>
    </section>
  </div>
</div>